{% set name = "cryptominisat" %}
{% set version = "5.6.0" %}
{% set sha256 = "bdcfd906defaac03ceaa213bcd0cc52694a75138042b66b34a9fc8fc2202e3c1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Use-CFLAGS-LDFLAGS-as-reported-by-sysconfig.patch
    - 0002-shared-breaks-build-on-OSX.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - cmake
    - python
    - setuptools
    - boost-cpp 1.66.0
    - zlib 1.2.11
    - m4ri 20140914
  run:
    - python
    - boost-cpp 1.66.0
    - zlib 1.2.11
    - m4ri 20140914

test:
  commands:
    - conda inspect linkages -p $PREFIX cryptominisat  # [not win]
    - conda inspect objects -p $PREFIX cryptominisat  # [osx]
    - echo -e '1 0\n-1 0' | cryptominisat5 | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5 | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
