{% set name = "cryptominisat" %}
{% set version = "5.12.1" %}
{% set build = 0 %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
    sha256: fa504ae5846c80a3650fda620383def7f3d1d9d5d08824b57e13c4d41e881d89
    folder: cryptominisat
    patches:
     - patches/fix_source_for_python.patch
     - patches/fix_tests.patch
  # We need to use source from git because
  # https://github.com/arminbiere/cadiback/blob/789329d8fcda851085ed72f1b07d8c3f46243b8a/generate#L7
  - git_url: https://github.com/meelgroup/cadiback.git
    git_rev: mate
    folder: cadiback
    patches:
     - patches/fix_cadiback.patch
  # The reason why cadical should be built from source here:
  # https://github.com/arminbiere/cadiback/blob/789329d8fcda851085ed72f1b07d8c3f46243b8a/README.md?plain=1#L7
  - git_url: https://github.com/meelgroup/cadical.git
    git_rev: mate-only-libraries-1.8.0
    folder: cadical

build:
  number: 0
  # After adding cadical and caiback as dependency to this package it cannot be build for windows
  # https://github.com/msoos/cryptominisat/commit/d1a51c9e7a96206bb2ddd07ae524e147b796e4b2
  skip: True  # [win]

# HACK: there's an issue with conda-build looping over python versions.  Forcing this here gives
#    us a clean slate for each build.
requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: libcryptominisat
    build:
      run_exports:
        - {{ pin_subpackage("libcryptominisat", max_pin="x.x") }}
    script: install-lib.sh  # [unix]
    script: install-lib.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler("cxx") }}
        - cmake
        - make  # [unix]
      host:
        - zlib
        - gmp
      run:
        - zlib
    test:
      commands:
        - test -e $PREFIX/lib/libcryptominisat5.5.12.dylib    # [osx]
        - test -e $PREFIX/lib/libcryptominisat5.so.5.12       # [linux]
        - IF NOT EXIST %LIBRARY_BIN%\cryptominisat5win.dll exit 1       # [win]
        - cryptominisat5 --zero-exit-status <unsat.cnf
        - cryptominisat5 --zero-exit-status <sat.cnf
        - cryptominisat5 <unsat.cnf | grep UNSATISFIABLE  # [unix]
        - cryptominisat5 <sat.cnf   | grep SATISFIABLE    # [unix]
        - cryptominisat5 <unsat.cnf | findstr UNSATISFIABLE  # [win]
        - cryptominisat5 <sat.cnf   | findstr SATISFIABLE    # [win]
      files:
        - sat.cnf
        - unsat.cnf

  - name: pycryptosat
    build:
      number: {{ build }}
      skip: True  # [py<35]
      script:
        - cd cryptominisat && python -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - setuptools >=42
        - pathlib
        - tomli
        - wheel
        - pip
        - gmp
        - {{ pin_subpackage('libcryptominisat', exact=True) }}
        - zlib
      run:
        - python
        - zlib
        - {{ pin_subpackage('libcryptominisat', exact=True) }}
    test:
      imports:
        - pycryptosat
      commands:
        - python cryptominisat/python/tests/test_pycryptosat.py
      source_files:
        - cryptominisat/python/tests

  - name: cryptominisat
    script: install-exec.sh   # [unix]
    script: install-exec.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - libboost-devel 1.88.0
        - {{ pin_subpackage('libcryptominisat', exact=True) }}
        - zlib
      run:
        - zlib
        - {{ pin_compatible("libboost", max_pin="x.x.x") }}
        - {{ pin_subpackage('libcryptominisat', exact=True) }}
    test:
      commands:
        - cryptominisat5 --zero-exit-status <unsat.cnf
        - cryptominisat5 --zero-exit-status <sat.cnf
        - cryptominisat5 <unsat.cnf | grep UNSATISFIABLE  # [unix]
        - cryptominisat5 <sat.cnf   | grep SATISFIABLE    # [unix]
        - cryptominisat5 <unsat.cnf | findstr UNSATISFIABLE  # [win]
        - cryptominisat5 <sat.cnf   | findstr SATISFIABLE    # [win]
      files:
        - sat.cnf
        - unsat.cnf

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat
  doc_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msarahan
    - msoos
    - saraedum
