travis:
  secure:
    BINSTAR_TOKEN: txBkKRLw1pZ8wODux/vMtPgwj6WrXgbnEBdjC/pLb9+KwN8BZ4/kXk48+Puki02VnFnOMuugYZdO4Vm0+M1Q9KQeLOiLW2SomE4UyEdx+exNapKHa+9V5FLK98cnR7EVWsF/VFsRlNEMRSLGWx8pS9HZucW77c0zzS3mYlGf611g+CSD6yNRqzyEo5aBW//CIPojNRb4N7yBe8o28SYUajFiNgfH9xyk9Uk2WBIODK+GsC47WiPPjuLgqRQyGH9B0wstJYOE2rjlPEz9bI+EdQBrJ+s67zq734x0rCVusPUZCeFW/36QFwjXYsirQ1rxcJveLVeX7y9OCu5vaVVlPT0ECkbNSortdSp/CbLVi6axRrBR7tFWlt9OOdsSxK1saGELRrnWMKPDKLoe2EgxKZ0b2yY7GKNkfJIKiBYXy/1Omc19LEuwWDZiJkF5Fsit2Mm8wk54lRoyfLApfNflwBs+EDAvS0g63+RJ2o/FjuV2F8RUvL8oJKR7Qn/GPeR2uRt8k8e+mgpIREXNm46hlkntsSGS1hMBul149Afa18eEmSVZLmqgz4ZC4x78qP64zfe11du1S8NoYlVIAHHRbFfARNCYl0MAadsENPvxHSFRoTrglX2FQX99m0at0ZEFxUNmOTVZEUOAglYPIljSjh0reZCZ3+WbIr3hur1tgns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
